org: '1252108578'
app: picgo
stage: dev
component: flask
name: flask-6upybor6v
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
  region: ap-beijing
  runtime: Python3.6
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: true
    timeout: 30
    memorySize: 128
